# Generated by Django 2.2.1 on 2019-06-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_now_remote_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='cryptoBTC_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.TextField()),
            ],
        ),
    ]
